title: Biostatistics Consulting Center
description: Placeholder for description
theme: just-the-docs

url: https://biostatistics-consulting-center.github.io

aux_links:
  BCC website: https://biostats.indiana.edu/index.html
