title: Biostatistics Consulting Center
# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/iusph_logo.jpg"
description: Placeholder for description
theme: just-the-docs

url: https://biostatistics-consulting-center.github.io

aux_links:
  BCC website: https://biostats.indiana.edu/index.html
