title: Biostatistics Consulting Center at IU SPH-Bloomingtom
description: Placeholder for description
theme: just-the-docs

url: https://biostatistics-consulting-center.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
